# Generated by Django 4.2.20 on 2025-04-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
